endpoints :
  # - name: "Test Config 1"
  #   url: "http://test1.com"
  #   interval_seconds: 6
  #   max_response_time_ms: 10
  #   timeout_second: 10
  #   expected_status_range: [200, 201]
  #   latency: 5

  - name: "First Config"
    url: "https://jsonplaceholder.typicode.com/todos/1"
    interval_seconds: 2
    max_response_time_ms: 10
    timeout_second: 10
    latency: 5

  - name: "Second Config"
    url: "https://jsonplaceholder.typicode.com/todos/1"
    interval_seconds: 6
    max_response_time_ms: 10
    timeout_second: 10
    latency: 5

